export const routeImports = {
  home: () => import('../../pages/HomePage/HomePage'),
  products: () => import('../../pages/ProductsPage/ProductsPage'),
  productEditor: () => import('../../pages/ProductEditorPage/ProductEditorPage'),
  shop: () => import('../../pages/ShopPage/ShopPage'),
  profile: () => import('../../pages/ProfilePage/ProfilePage'),
  warehouses: () => import('../../pages/WarehousesPage/WarehousesPage'),
  stock: () => import('../../pages/StockPage/StockPage'),
  orders: () => import('../../pages/OrdersPage/OrdersPage'),
  delivery: () => import('../../pages/DeliveryPage/DeliveryPage'),
  settings: () => import('../../pages/SettingsPage/SettingsPage'),
  support: () => import('../../pages/SupportPage/SupportPage'),
  users: () => import('../../pages/UsersPage/UsersPage'),
  userEditor: () => import('../../pages/UserEditorPage/UserEditorPage'),
  storefrontShop: () => import('../../pages/StorefrontShopPage/StorefrontShopPage'),
  storefrontProduct: () => import('../../pages/StorefrontProductPage/StorefrontProductPage'),
  adminShops: () => import('../../pages/AdminShopsPage/AdminShopsPage'),
  adminOrders: () => import('../../pages/AdminOrdersPage/AdminOrdersPage'),
  adminOrderDetail: () => import('../../pages/AdminOrderDetailPage/AdminOrderDetailPage'),
  adminProducts: () => import('../../pages/AdminProductsPage/AdminProductsPage'),
  adminProductDetail: () => import('../../pages/AdminProductDetailPage/AdminProductDetailPage'),
  adminUsers: () => import('../../pages/AdminUsersPage/AdminUsersPage'),
  adminUserCreate: () => import('../../pages/AdminUserCreatePage/AdminUserCreatePage'),
  adminUserDetail: () => import('../../pages/AdminUserDetailPage/AdminUserDetailPage'),
  adminFinance: () => import('../../pages/AdminFinancePage/AdminFinancePage'),
  adminAudit: () => import('../../pages/AdminAuditPage/AdminAuditPage'),
  adminSystemHealth: () => import('../../pages/AdminSystemHealthPage/AdminSystemHealthPage'),
  adminOverview: () => import('../../pages/AdminOverviewPage/AdminOverviewPage'),
};

const routePreloaders: Array<[
  prefix: string,
  preload: () => Promise<unknown>,
]> = [
  ['/dokon/', routeImports.storefrontShop],
  ['/mahsulot/', routeImports.storefrontProduct],
  ['/products/new', routeImports.productEditor],
  ['/products/', routeImports.productEditor],
  ['/products', routeImports.products],
  ['/shop', routeImports.shop],
  ['/warehouses', routeImports.warehouses],
  ['/stock', routeImports.stock],
  ['/orders', routeImports.orders],
  ['/delivery', routeImports.delivery],
  ['/profile', routeImports.profile],
  ['/settings', routeImports.settings],
  ['/support', routeImports.support],
  ['/users/new', routeImports.userEditor],
  ['/users', routeImports.users],
  ['/admin/shops', routeImports.adminShops],
  ['/admin/overview', routeImports.adminOverview],
  ['/admin/orders/', routeImports.adminOrderDetail],
  ['/admin/orders', routeImports.adminOrders],
  ['/admin/products/', routeImports.adminProductDetail],
  ['/admin/products', routeImports.adminProducts],
  ['/admin/users/new', routeImports.adminUserCreate],
  ['/admin/users/', routeImports.adminUserDetail],
  ['/admin/users', routeImports.adminUsers],
  ['/admin/finance', routeImports.adminFinance],
  ['/admin/audit-logs', routeImports.adminAudit],
  ['/admin/profile', routeImports.profile],
  ['/admin/system-settings', routeImports.adminSystemHealth],
  ['/', routeImports.home],
];

export function prefetchRoute(path: string): void {
  const route = routePreloaders.find(([prefix]) =>
    prefix === '/' ? path === '/' : path.startsWith(prefix),
  );
  if (route) void route[1]();
}
